// <auto-generated />
using System;
using ManagementOfForeigners.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementOfForeigners.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615072105_MakeForeignerAccountNullable")]
    partial class MakeForeignerAccountNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.BaoCaoViPham", b =>
                {
                    b.Property<string>("MaBaoCao")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MaCanBo")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MaNguoiNuocNgoai")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDungBaoCao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("MaCanBo");

                    b.HasIndex("MaNguoiNuocNgoai");

                    b.ToTable("BaoCaoViPham", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CanBo", b =>
                {
                    b.Property<string>("MaCanBo")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("CapQuanLy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViCongTac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayCapCCCD")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NoiCapCCCD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("char(12)")
                        .IsFixedLength();

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCanBo");

                    b.HasIndex("MaPhuongXa");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.ToTable("CanBo", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CanhBaoViPham", b =>
                {
                    b.Property<int>("MaCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCanhBao"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("LoaiViPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaCanBo")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MaNguoiNuocNgoai")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MucDoViPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDungCanhBao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCanhBao");

                    b.HasIndex("MaCanBo");

                    b.HasIndex("MaNguoiNuocNgoai");

                    b.ToTable("CanhBaoViPham", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.ChuCoSoLuuTru", b =>
                {
                    b.Property<string>("MaChuCoSo")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("DiaChiThuongTru")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayCapCCCD")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NoiCapCCCD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoCCCD")
                        .IsRequired()
                        .HasColumnType("char(12)")
                        .IsFixedLength();

                    b.HasKey("MaChuCoSo");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.ToTable("ChuCoSoLuuTru", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CoSoLuuTru", b =>
                {
                    b.Property<string>("MaCoSoLuuTru")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaChuCoSo")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<int>("MaPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("MaSoKinhDoanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("SoPhong")
                        .HasColumnType("int");

                    b.Property<int?>("SucChuaToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenCoSo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("MaCoSoLuuTru");

                    b.HasIndex("MaChuCoSo");

                    b.HasIndex("MaPhuongXa");

                    b.ToTable("CoSoLuuTru", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.HoSoKhaiBaoTamTru", b =>
                {
                    b.Property<string>("MaHSKhaiBao")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("DiaChiLuuTru")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaCoSoLuuTru")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MucDichLuuTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKhaiBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaHSKhaiBao");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("HoSoKhaiBaoTamTru", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.LichSuCapNhatThongTinCaNhan", b =>
                {
                    b.Property<string>("MaLSCapNhat")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("GiaTriCu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GiaTriMoi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDoCapNhat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TruongCapNhat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLSCapNhat");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("LichSuCapNhatThongTinCaNhan", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.LichSuCuTru", b =>
                {
                    b.Property<string>("MaLSLuuTru")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaCoSoLuuTru")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("MaNguoiNuocNgoai")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<string>("Phong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLSLuuTru");

                    b.HasIndex("MaCoSoLuuTru");

                    b.HasIndex("MaNguoiNuocNgoai");

                    b.ToTable("LichSuCuTru", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", b =>
                {
                    b.Property<string>("MaNguoiNuocNgoai")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiVisa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayCapHoChieu")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayHetHanHoChieu")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayHetHanVisa")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoHoChieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiNuocNgoai");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.HasIndex("SoHoChieu")
                        .IsUnique();

                    b.ToTable("NguoiNuocNgoai", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.PhuongXa", b =>
                {
                    b.Property<int>("MaPhuongXa")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuongXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhuongXa");

                    b.ToTable("PhuongXa", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.QuyenHan", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MoTaQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("QuyenHan", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MoTaVaiTro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.BaoCaoViPham", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.CanBo", "CanBo")
                        .WithMany("BaoCaoViPhams")
                        .HasForeignKey("MaCanBo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", "NguoiNuocNgoai")
                        .WithMany("BaoCaoViPhams")
                        .HasForeignKey("MaNguoiNuocNgoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanBo");

                    b.Navigation("NguoiNuocNgoai");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CanBo", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.PhuongXa", "PhuongXa")
                        .WithMany("CanBos")
                        .HasForeignKey("MaPhuongXa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagementOfForeigners.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("CanBo")
                        .HasForeignKey("ManagementOfForeigners.Models.Entities.CanBo", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhuongXa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CanhBaoViPham", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.CanBo", "CanBo")
                        .WithMany("CanhBaoViPhams")
                        .HasForeignKey("MaCanBo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", "NguoiNuocNgoai")
                        .WithMany("CanhBaoViPhams")
                        .HasForeignKey("MaNguoiNuocNgoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanBo");

                    b.Navigation("NguoiNuocNgoai");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.ChuCoSoLuuTru", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("ChuCoSoLuuTru")
                        .HasForeignKey("ManagementOfForeigners.Models.Entities.ChuCoSoLuuTru", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CoSoLuuTru", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.ChuCoSoLuuTru", "ChuCoSoLuuTru")
                        .WithMany("CoSoLuuTrus")
                        .HasForeignKey("MaChuCoSo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagementOfForeigners.Models.Entities.PhuongXa", "PhuongXa")
                        .WithMany("CoSoLuuTrus")
                        .HasForeignKey("MaPhuongXa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuCoSoLuuTru");

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.HoSoKhaiBaoTamTru", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("HoSoKhaiBaoTamTrus")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagementOfForeigners.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("HoSoKhaiBaoTamTrus")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.LichSuCapNhatThongTinCaNhan", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuCapNhats")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.LichSuCuTru", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.CoSoLuuTru", "CoSoLuuTru")
                        .WithMany("LichSuCuTrus")
                        .HasForeignKey("MaCoSoLuuTru")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", "NguoiNuocNgoai")
                        .WithMany("LichSuCuTrus")
                        .HasForeignKey("MaNguoiNuocNgoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoSoLuuTru");

                    b.Navigation("NguoiNuocNgoai");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NguoiNuocNgoai")
                        .HasForeignKey("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.QuyenHan", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("QuyenHans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("ManagementOfForeigners.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CanBo", b =>
                {
                    b.Navigation("BaoCaoViPhams");

                    b.Navigation("CanhBaoViPhams");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.ChuCoSoLuuTru", b =>
                {
                    b.Navigation("CoSoLuuTrus");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.CoSoLuuTru", b =>
                {
                    b.Navigation("HoSoKhaiBaoTamTrus");

                    b.Navigation("LichSuCuTrus");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.NguoiNuocNgoai", b =>
                {
                    b.Navigation("BaoCaoViPhams");

                    b.Navigation("CanhBaoViPhams");

                    b.Navigation("LichSuCuTrus");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.PhuongXa", b =>
                {
                    b.Navigation("CanBos");

                    b.Navigation("CoSoLuuTrus");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("CanBo");

                    b.Navigation("ChuCoSoLuuTru");

                    b.Navigation("HoSoKhaiBaoTamTrus");

                    b.Navigation("LichSuCapNhats");

                    b.Navigation("NguoiNuocNgoai");
                });

            modelBuilder.Entity("ManagementOfForeigners.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("QuyenHans");

                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
